site_name: test_stale_action
site_description: FIXME
site_author: Sven Nowotnik
repo_url: http://FIXME

theme:
  name: material

nav:
  - Introduction: index.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

plugins:
  - search:
      lang: en
